### ISSUE TITLE
hi! petrassurna

### ISSUE THREAD

**Issue by itunc1980** [petrassurna/DotNetSiteSearch#3]
hello petrassurna

When I run Umbraco12SampleSite, I see that I am searching on nodeNames. How can I perform the search function on other Properties? If I want to return a summary of the search results, do I run into language character problems? For example, Ş->S , İ->I , Ö->O , Ğ->G , Ç->C , Ü->U etc. So I would like special characters to appear as well, is that possible?

Best wishes.
Thank you,

**Comment by petrassurna** [comment]
Hi there,

I have fixed the language character problem in release 0.6675.
Thanks for pointing it out!

I don't intend to search on other properties at this stage. I always saw this project as a quick page search, not a complex search such a Examine can provide. Note you can exclude certain nodes with the usitesearch-exclude html attribute as covered in the help.
